version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=blockchain_tracker
      - MORALIS_API_KEY=${MORALIS_API_KEY:?MORALIS_API_KEY is required}
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=${SMTP_USER:?SMTP_USER is required}
      - SMTP_PASS=${SMTP_PASS:?SMTP_PASS is required}
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blockchain_tracker
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 